In [1]:
import numpy as np
x=[9,17,20,19,20,23]
y=[22,34,29,33,42,32]
correlacao = np.corrcoef(x, y)
print(correlacao)

[[1.         0.65373441]
 [0.65373441 1.        ]]


In [2]:
import numpy as np
x=[4,8,7,12,12,8,7,8,4,7]
y=[4,5,5,6,5,4,4,5,6,6]
correlacao = np.corrcoef(x, y)
print(correlacao)

[[1.         0.20085546]
 [0.20085546 1.        ]]


In [3]:
import numpy as np
x=[-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,1,1,1,1,1,1]
y=[-2,0,0,0,0,2,-2,0,0,0,0,2,-2,0,0,0,0,2]
correlacao = np.corrcoef(x, y)
print(correlacao)

[[1. 0.]
 [0. 1.]]


In [7]:
x=[4,8,7,12,12,8,7,8,4,7]
y=[4,5,5,6,5,4,4,5,6,6]

In [13]:
import sympy as sy
import numpy as np
from sklearn.linear_model import LinearRegression
x = np.array(x)
x = x.reshape(-1, 1)
modelo = LinearRegression().fit(x, y)
print(modelo.intercept_)
print (modelo.coef_)


4.534039334341906
[0.06051437]


In [12]:
from sklearn.metrics import r2_score
R2 = r2_score(y, modelo.predict(x))
print('R2:', R2)

R2: 0.040342914775592376


In [1]:
x=[1,2,3,4]
y=[4.1,0.6,0.3,3.2]

In [2]:
import sympy as sy
import numpy as np
from sklearn.linear_model import LinearRegression
x = np.array(x)
x = x.reshape(-1, 1)
modelo = LinearRegression().fit(x, y)
print(modelo.intercept_)
print (modelo.coef_)

2.8
[-0.3]


In [4]:
x=[1,2,3,4]
y=[4.1,0.6,0.3,3.2]
correlacao = np.corrcoef(x, y)
print(correlacao)

[[ 1.         -0.20517168]
 [-0.20517168  1.        ]]


In [4]:
import numpy as np
x=[2, 4, 5, 8, 9, 10, 5];
y=[4, 9, 7, 10, 11, 15, 8];
correlacao = np.corrcoef(x, y)
print(correlacao)

[[1.         0.91382995]
 [0.91382995 1.        ]]
